# Generated by Django 2.2.11 on 2020-03-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20200317_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
